
#define INDIVIDUALS_ANCESTRAL_GENOTYPE 0
#define INDIVIDUALS_PERFECTLY_ADAPTED_GENOTYPE 1
#define INDIVIDUALS_RANDOM_GENOTYPE 2

#define NORMAL_LINKAGE 0
#define ALL_LOCI_INDEPENDENT 1


#define MALE 0
#define FEMALE 1
